### ISSUE TITLE
Skrčenje avtorjev

### ISSUE THREAD

**Issue by TomazErjavec** [DARIAH-SI/suss#1]
Če je v ediciji dosti avtorjev - kot jih pri ŠUSS je - je treba če miško, da sploh prideš do naslova, cf. https://dariah-si.github.io/suss/cip.html. Mogoče bi bilo lepše, če bi bilo ločeni samo z vejico ali podpičjem?

**Comment by andrejPancur** [comment]
Dal avtorje v eno vrstico, ločeni so z vejico
